// USER LOGIN / REGISTRATION
export const USER_LOADED = 'USER_LOADED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

// USER ACCOUNT
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_SHIPPING = 'UPDATE_SHIPPING';
export const UPDATE_BILLING = 'UPDATE_BILLING';
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const ACCOUNT_ERROR = 'ACCOUNT_ERROR';

// USER CART
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_ITEM = 'CLEAR_ITEM';
export const CART_ERROR = 'CART_ERROR';