// PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

// NEWSLETTER
export const ADD_NEWSLETTER = 'ADD_NEWSLETTER';
export const REMOVE_NEWSLETTER = 'REMOVE_NEWSLETTER';
export const NEWSLETTER_ERROR = 'NEWSLETTER_ERROR';
